Feature/fragment builder
Omega-R/OmegaIntentBuilder pull request #75
Opened 2018-03-26 08:21 UTC by R12rus

2018-03-27 07:16 UTC, anton-knyazev requested changes

2018-03-27 07:16 UTC, anton-knyazev commented on README.md
> +    }
один конструтор

2018-03-27 07:16 UTC, anton-knyazev commented on core/src/main/java/com/omega_r/libs/omegaintentbuilder/bundle/BundleBuilder.kt
> +    fun putExtra(bundle: Bundle): BundleBuilder {
fun putExtra(name: String, bundle: Bundle): BundleBuilder

2018-03-27 07:16 UTC, anton-knyazev commented on examples/src/main/java/com/omega_r/omegaintentbuilder/MainActivity.java
> +                .appActivity()
appActivities

2018-03-28 05:55 UTC, R12rus commented on README.md
> +    }
Caused by: java.lang.InstantiationException: java.lang.Class<com.omega_r.omegaintentbuilder.service_example.TestService> has no zero argument constructor

2018-03-28 07:03 UTC, anton-knyazev approved these changes

2018-03-28 07:03 UTC, merged